services:
  ato:
    image: php:8.3-apache
    container_name: ato
    ports:
      - "11451:80"
    volumes:
      - ./:/var/www/html
    entrypoint: /bin/sh -c "chown -R 33:33 /var/www/html/data && apache2-foreground"
    restart: unless-stopped
