/* Auto generated: BP card resource map.
   You can continue editing it with this marker tool. */
window.AIBP_BP_RESOURCE_MAP = {
    "THE_NIETZSCJEAN":  {
                            "THE_NIETZSCJEAN_BP_III_004.jpg":  {
                                                                   "BC":  0,
                                                                   "CM":  0,
                                                                   "EF":  0,
                                                                   "URM":  0,
                                                                   "LS":  1,
                                                                   "CT":  0,
                                                                   "SM":  0,
                                                                   "RT":  0,
                                                                   "UA":  1
                                                               },
                            "THE_NIETZSCJEAN_BP_I_006.jpg":  {
                                                                 "BC":  0,
                                                                 "CM":  0,
                                                                 "EF":  0,
                                                                 "URM":  0,
                                                                 "LS":  0,
                                                                 "CT":  0,
                                                                 "SM":  1,
                                                                 "RT":  0,
                                                                 "UA":  0
                                                             },
                            "THE_NIETZSCJEAN_BP_III_003.jpg":  {
                                                                   "BC":  0,
                                                                   "CM":  0,
                                                                   "EF":  0,
                                                                   "URM":  0,
                                                                   "LS":  1,
                                                                   "CT":  0,
                                                                   "SM":  1,
                                                                   "RT":  0,
                                                                   "UA":  0
                                                               },
                            "THE_NIETZSCJEAN_BP_I_004.jpg":  {
                                                                 "BC":  0,
                                                                 "CM":  0,
                                                                 "EF":  0,
                                                                 "URM":  0,
                                                                 "LS":  0,
                                                                 "CT":  0,
                                                                 "SM":  0,
                                                                 "RT":  0,
                                                                 "UA":  2
                                                             },
                            "THE_NIETZSCJEAN_BP_III_001.jpg":  {
                                                                   "BC":  0,
                                                                   "CM":  0,
                                                                   "EF":  0,
                                                                   "URM":  0,
                                                                   "LS":  0,
                                                                   "CT":  0,
                                                                   "SM":  1,
                                                                   "RT":  0,
                                                                   "UA":  2
                                                               },
                            "THE_NIETZSCJEAN_BP_II_005.jpg":  {
                                                                  "BC":  0,
                                                                  "CM":  0,
                                                                  "EF":  0,
                                                                  "URM":  0,
                                                                  "LS":  1,
                                                                  "CT":  0,
                                                                  "SM":  0,
                                                                  "RT":  0,
                                                                  "UA":  0
                                                              },
                            "THE_NIETZSCJEAN_BP_III_006.jpg":  {
                                                                   "BC":  0,
                                                                   "CM":  0,
                                                                   "EF":  0,
                                                                   "URM":  0,
                                                                   "LS":  1,
                                                                   "CT":  0,
                                                                   "SM":  0,
                                                                   "RT":  0,
                                                                   "UA":  2
                                                               },
                            "THE_NIETZSCJEAN_BP_II_002.jpg":  {
                                                                  "BC":  0,
                                                                  "CM":  0,
                                                                  "EF":  0,
                                                                  "URM":  0,
                                                                  "LS":  1,
                                                                  "CT":  0,
                                                                  "SM":  1,
                                                                  "RT":  0,
                                                                  "UA":  0
                                                              },
                            "THE_NIETZSCJEAN_BP_II_006.jpg":  {
                                                                  "BC":  0,
                                                                  "CM":  0,
                                                                  "EF":  0,
                                                                  "URM":  0,
                                                                  "LS":  0,
                                                                  "CT":  0,
                                                                  "SM":  0,
                                                                  "RT":  0,
                                                                  "UA":  2
                                                              },
                            "THE_NIETZSCJEAN_BP_I_005.jpg":  {
                                                                 "BC":  0,
                                                                 "CM":  0,
                                                                 "EF":  0,
                                                                 "URM":  0,
                                                                 "LS":  0,
                                                                 "CT":  0,
                                                                 "SM":  0,
                                                                 "RT":  0,
                                                                 "UA":  2
                                                             },
                            "THE_NIETZSCJEAN_BP_III_005.jpg":  {
                                                                   "BC":  0,
                                                                   "CM":  0,
                                                                   "EF":  0,
                                                                   "URM":  0,
                                                                   "LS":  0,
                                                                   "CT":  0,
                                                                   "SM":  1,
                                                                   "RT":  0,
                                                                   "UA":  1
                                                               },
                            "THE_NIETZSCJEAN_BP_II_003.jpg":  {
                                                                  "BC":  0,
                                                                  "CM":  0,
                                                                  "EF":  0,
                                                                  "URM":  0,
                                                                  "LS":  0,
                                                                  "CT":  0,
                                                                  "SM":  0,
                                                                  "RT":  0,
                                                                  "UA":  2
                                                              },
                            "THE_NIETZSCJEAN_BP_II_004.jpg":  {
                                                                  "BC":  0,
                                                                  "CM":  0,
                                                                  "EF":  0,
                                                                  "URM":  0,
                                                                  "LS":  1,
                                                                  "CT":  0,
                                                                  "SM":  1,
                                                                  "RT":  0,
                                                                  "UA":  0
                                                              },
                            "THE_NIETZSCJEAN_BP_I_003.jpg":  {
                                                                 "BC":  0,
                                                                 "CM":  0,
                                                                 "EF":  0,
                                                                 "URM":  0,
                                                                 "LS":  0,
                                                                 "CT":  0,
                                                                 "SM":  0,
                                                                 "RT":  0,
                                                                 "UA":  2
                                                             },
                            "THE_NIETZSCJEAN_BP_II_001.jpg":  {
                                                                  "BC":  0,
                                                                  "CM":  0,
                                                                  "EF":  0,
                                                                  "URM":  0,
                                                                  "LS":  0,
                                                                  "CT":  0,
                                                                  "SM":  1,
                                                                  "RT":  0,
                                                                  "UA":  0
                                                              },
                            "THE_NIETZSCJEAN_BP_I_001.jpg":  {
                                                                 "BC":  0,
                                                                 "CM":  0,
                                                                 "EF":  0,
                                                                 "URM":  0,
                                                                 "LS":  0,
                                                                 "CT":  0,
                                                                 "SM":  0,
                                                                 "RT":  0,
                                                                 "UA":  2
                                                             },
                            "THE_NIETZSCJEAN_BP_I_002.jpg":  {
                                                                 "BC":  0,
                                                                 "CM":  0,
                                                                 "EF":  0,
                                                                 "URM":  0,
                                                                 "LS":  1,
                                                                 "CT":  0,
                                                                 "SM":  0,
                                                                 "RT":  0,
                                                                 "UA":  0
                                                             },
                            "THE_NIETZSCJEAN_BP_III_002.jpg":  {
                                                                   "BC":  0,
                                                                   "CM":  0,
                                                                   "EF":  0,
                                                                   "URM":  0,
                                                                   "LS":  0,
                                                                   "CT":  0,
                                                                   "SM":  1,
                                                                   "RT":  0,
                                                                   "UA":  1
                                                               }
                        },
    "CYCLONUS":  {
                     "CYCLONUS_BP_III_003.jpg":  {
                                                     "BC":  0,
                                                     "CM":  1,
                                                     "EF":  0,
                                                     "URM":  0,
                                                     "LS":  0,
                                                     "CT":  0,
                                                     "SM":  0,
                                                     "RT":  0,
                                                     "UA":  1
                                                 },
                     "CYCLONUS_BP_II_001.jpg":  {
                                                    "BC":  1,
                                                    "CM":  0,
                                                    "EF":  0,
                                                    "URM":  0,
                                                    "LS":  0,
                                                    "CT":  0,
                                                    "SM":  0,
                                                    "RT":  0,
                                                    "UA":  0
                                                },
                     "CYCLONUS_BP_III_001.jpg":  {
                                                     "BC":  1,
                                                     "CM":  0,
                                                     "EF":  0,
                                                     "URM":  0,
                                                     "LS":  0,
                                                     "CT":  0,
                                                     "SM":  0,
                                                     "RT":  0,
                                                     "UA":  1
                                                 },
                     "CYCLONUS_BP_III_002.jpg":  {
                                                     "BC":  0,
                                                     "CM":  1,
                                                     "EF":  0,
                                                     "URM":  0,
                                                     "LS":  0,
                                                     "CT":  0,
                                                     "SM":  0,
                                                     "RT":  0,
                                                     "UA":  1
                                                 },
                     "CYCLONUS_BP_I_005.jpg":  {
                                                   "BC":  0,
                                                   "CM":  0,
                                                   "EF":  0,
                                                   "URM":  0,
                                                   "LS":  0,
                                                   "CT":  0,
                                                   "SM":  0,
                                                   "RT":  0,
                                                   "UA":  1
                                               },
                     "CYCLONUS_BP_III_005.jpg":  {
                                                     "BC":  0,
                                                     "CM":  1,
                                                     "EF":  0,
                                                     "URM":  0,
                                                     "LS":  0,
                                                     "CT":  0,
                                                     "SM":  0,
                                                     "RT":  0,
                                                     "UA":  1
                                                 },
                     "CYCLONUS_BP_II_006.jpg":  {
                                                    "BC":  0,
                                                    "CM":  1,
                                                    "EF":  0,
                                                    "URM":  0,
                                                    "LS":  0,
                                                    "CT":  0,
                                                    "SM":  0,
                                                    "RT":  0,
                                                    "UA":  0
                                                },
                     "CYCLONUS_BP_I_006.jpg":  {
                                                   "BC":  0,
                                                   "CM":  0,
                                                   "EF":  0,
                                                   "URM":  0,
                                                   "LS":  0,
                                                   "CT":  0,
                                                   "SM":  0,
                                                   "RT":  0,
                                                   "UA":  1
                                               },
                     "CYCLONUS_BP_III_006.jpg":  {
                                                     "BC":  1,
                                                     "CM":  0,
                                                     "EF":  0,
                                                     "URM":  0,
                                                     "LS":  0,
                                                     "CT":  0,
                                                     "SM":  0,
                                                     "RT":  0,
                                                     "UA":  1
                                                 },
                     "CYCLONUS_BP_II_004.jpg":  {
                                                    "BC":  0,
                                                    "CM":  1,
                                                    "EF":  0,
                                                    "URM":  0,
                                                    "LS":  0,
                                                    "CT":  0,
                                                    "SM":  0,
                                                    "RT":  0,
                                                    "UA":  0
                                                },
                     "CYCLONUS_BP_I_004.jpg":  {
                                                   "BC":  0,
                                                   "CM":  0,
                                                   "EF":  0,
                                                   "URM":  0,
                                                   "LS":  0,
                                                   "CT":  0,
                                                   "SM":  0,
                                                   "RT":  0,
                                                   "UA":  1
                                               },
                     "CYCLONUS_BP_III_004.jpg":  {
                                                     "BC":  1,
                                                     "CM":  0,
                                                     "EF":  0,
                                                     "URM":  0,
                                                     "LS":  0,
                                                     "CT":  0,
                                                     "SM":  0,
                                                     "RT":  0,
                                                     "UA":  1
                                                 },
                     "CYCLONUS_BP_II_005.jpg":  {
                                                    "BC":  1,
                                                    "CM":  0,
                                                    "EF":  0,
                                                    "URM":  0,
                                                    "LS":  0,
                                                    "CT":  0,
                                                    "SM":  0,
                                                    "RT":  0,
                                                    "UA":  0
                                                },
                     "CYCLONUS_BP_II_002.jpg":  {
                                                    "BC":  1,
                                                    "CM":  0,
                                                    "EF":  0,
                                                    "URM":  0,
                                                    "LS":  0,
                                                    "CT":  0,
                                                    "SM":  0,
                                                    "RT":  0,
                                                    "UA":  0
                                                },
                     "CYCLONUS_BP_I_002.jpg":  {
                                                   "BC":  0,
                                                   "CM":  0,
                                                   "EF":  0,
                                                   "URM":  0,
                                                   "LS":  0,
                                                   "CT":  0,
                                                   "SM":  0,
                                                   "RT":  0,
                                                   "UA":  1
                                               },
                     "CYCLONUS_BP_I_003.jpg":  {
                                                   "BC":  0,
                                                   "CM":  0,
                                                   "EF":  0,
                                                   "URM":  0,
                                                   "LS":  0,
                                                   "CT":  0,
                                                   "SM":  0,
                                                   "RT":  0,
                                                   "UA":  1
                                               },
                     "CYCLONUS_BP_I_001.jpg":  {
                                                   "BC":  0,
                                                   "CM":  0,
                                                   "EF":  0,
                                                   "URM":  0,
                                                   "LS":  0,
                                                   "CT":  0,
                                                   "SM":  0,
                                                   "RT":  0,
                                                   "UA":  1
                                               },
                     "CYCLONUS_BP_II_003.jpg":  {
                                                    "BC":  0,
                                                    "CM":  1,
                                                    "EF":  0,
                                                    "URM":  0,
                                                    "LS":  0,
                                                    "CT":  0,
                                                    "SM":  0,
                                                    "RT":  0,
                                                    "UA":  0
                                                }
                 },
    "CHIMERA_METASTASIOS":  {
                                "CHIMERA_METASTASIOS_BP_II_001.jpg":  {
                                                                          "BC":  0,
                                                                          "CM":  0,
                                                                          "EF":  0,
                                                                          "URM":  1,
                                                                          "LS":  0,
                                                                          "CT":  0,
                                                                          "SM":  0,
                                                                          "RT":  0,
                                                                          "UA":  0
                                                                      },
                                "CHIMERA_METASTASIOS_BP_I_004.jpg":  {
                                                                         "BC":  0,
                                                                         "CM":  0,
                                                                         "EF":  0,
                                                                         "URM":  0,
                                                                         "LS":  0,
                                                                         "CT":  0,
                                                                         "SM":  0,
                                                                         "RT":  0,
                                                                         "UA":  1
                                                                     },
                                "CHIMERA_METASTASIOS_BP_II_006.jpg":  {
                                                                          "BC":  0,
                                                                          "CM":  0,
                                                                          "EF":  0,
                                                                          "URM":  1,
                                                                          "LS":  0,
                                                                          "CT":  0,
                                                                          "SM":  0,
                                                                          "RT":  0,
                                                                          "UA":  0
                                                                      },
                                "CHIMERA_METASTASIOS_BP_II_002.jpg":  {
                                                                          "BC":  0,
                                                                          "CM":  0,
                                                                          "EF":  0,
                                                                          "URM":  0,
                                                                          "LS":  0,
                                                                          "CT":  2,
                                                                          "SM":  0,
                                                                          "RT":  0,
                                                                          "UA":  0
                                                                      },
                                "CHIMERA_METASTASIOS_BP_I_002.jpg":  {
                                                                         "BC":  0,
                                                                         "CM":  0,
                                                                         "EF":  0,
                                                                         "URM":  0,
                                                                         "LS":  0,
                                                                         "CT":  0,
                                                                         "SM":  0,
                                                                         "RT":  0,
                                                                         "UA":  1
                                                                     },
                                "CHIMERA_METASTASIOS_BP_III_006.jpg":  {
                                                                           "BC":  0,
                                                                           "CM":  0,
                                                                           "EF":  0,
                                                                           "URM":  1,
                                                                           "LS":  0,
                                                                           "CT":  0,
                                                                           "SM":  0,
                                                                           "RT":  0,
                                                                           "UA":  1
                                                                       },
                                "CHIMERA_METASTASIOS_BP_II_004.jpg":  {
                                                                          "BC":  0,
                                                                          "CM":  0,
                                                                          "EF":  0,
                                                                          "URM":  1,
                                                                          "LS":  0,
                                                                          "CT":  0,
                                                                          "SM":  0,
                                                                          "RT":  0,
                                                                          "UA":  0
                                                                      },
                                "CHIMERA_METASTASIOS_BP_I_005.jpg":  {
                                                                         "BC":  0,
                                                                         "CM":  0,
                                                                         "EF":  0,
                                                                         "URM":  0,
                                                                         "LS":  0,
                                                                         "CT":  0,
                                                                         "SM":  0,
                                                                         "RT":  0,
                                                                         "UA":  1
                                                                     },
                                "CHIMERA_METASTASIOS_BP_III_004.jpg":  {
                                                                           "BC":  0,
                                                                           "CM":  0,
                                                                           "EF":  0,
                                                                           "URM":  1,
                                                                           "LS":  0,
                                                                           "CT":  0,
                                                                           "SM":  0,
                                                                           "RT":  0,
                                                                           "UA":  1
                                                                       },
                                "CHIMERA_METASTASIOS_BP_I_003.jpg":  {
                                                                         "BC":  0,
                                                                         "CM":  0,
                                                                         "EF":  0,
                                                                         "URM":  0,
                                                                         "LS":  0,
                                                                         "CT":  0,
                                                                         "SM":  0,
                                                                         "RT":  0,
                                                                         "UA":  1
                                                                     },
                                "CHIMERA_METASTASIOS_BP_III_002.jpg":  {
                                                                           "BC":  0,
                                                                           "CM":  0,
                                                                           "EF":  0,
                                                                           "URM":  0,
                                                                           "LS":  0,
                                                                           "CT":  1,
                                                                           "SM":  0,
                                                                           "RT":  0,
                                                                           "UA":  1
                                                                       },
                                "CHIMERA_METASTASIOS_BP_I_001.jpg":  {
                                                                         "BC":  0,
                                                                         "CM":  0,
                                                                         "EF":  0,
                                                                         "URM":  0,
                                                                         "LS":  0,
                                                                         "CT":  0,
                                                                         "SM":  0,
                                                                         "RT":  0,
                                                                         "UA":  1
                                                                     },
                                "CHIMERA_METASTASIOS_BP_II_005.jpg":  {
                                                                          "BC":  0,
                                                                          "CM":  0,
                                                                          "EF":  0,
                                                                          "URM":  0,
                                                                          "LS":  0,
                                                                          "CT":  1,
                                                                          "SM":  0,
                                                                          "RT":  0,
                                                                          "UA":  0
                                                                      },
                                "CHIMERA_METASTASIOS_BP_III_005.jpg":  {
                                                                           "BC":  0,
                                                                           "CM":  0,
                                                                           "EF":  0,
                                                                           "URM":  0,
                                                                           "LS":  0,
                                                                           "CT":  1,
                                                                           "SM":  0,
                                                                           "RT":  0,
                                                                           "UA":  1
                                                                       },
                                "CHIMERA_METASTASIOS_BP_III_003.jpg":  {
                                                                           "BC":  0,
                                                                           "CM":  0,
                                                                           "EF":  0,
                                                                           "URM":  1,
                                                                           "LS":  0,
                                                                           "CT":  0,
                                                                           "SM":  0,
                                                                           "RT":  0,
                                                                           "UA":  1
                                                                       },
                                "CHIMERA_METASTASIOS_BP_II_003.jpg":  {
                                                                          "BC":  0,
                                                                          "CM":  0,
                                                                          "EF":  0,
                                                                          "URM":  0,
                                                                          "LS":  0,
                                                                          "CT":  2,
                                                                          "SM":  0,
                                                                          "RT":  0,
                                                                          "UA":  0
                                                                      },
                                "CHIMERA_METASTASIOS_BP_I_006.jpg":  {
                                                                         "BC":  0,
                                                                         "CM":  0,
                                                                         "EF":  0,
                                                                         "URM":  0,
                                                                         "LS":  0,
                                                                         "CT":  0,
                                                                         "SM":  0,
                                                                         "RT":  0,
                                                                         "UA":  1
                                                                     },
                                "CHIMERA_METASTASIOS_BP_III_001.jpg":  {
                                                                           "BC":  0,
                                                                           "CM":  0,
                                                                           "EF":  0,
                                                                           "URM":  0,
                                                                           "LS":  0,
                                                                           "CT":  1,
                                                                           "SM":  0,
                                                                           "RT":  0,
                                                                           "UA":  1
                                                                       }
                            },
    "THE_BURDEN":  {
                       "THE_BURDEN_BP_II_004.jpg":  {
                                                        "BC":  0,
                                                        "CM":  0,
                                                        "EF":  4,
                                                        "URM":  0,
                                                        "LS":  0,
                                                        "CT":  0,
                                                        "SM":  0,
                                                        "RT":  0,
                                                        "UA":  0
                                                    },
                       "THE_BURDEN_BP_III_005.jpg":  {
                                                         "BC":  0,
                                                         "CM":  0,
                                                         "EF":  2,
                                                         "URM":  0,
                                                         "LS":  0,
                                                         "CT":  0,
                                                         "SM":  0,
                                                         "RT":  2,
                                                         "UA":  0
                                                     },
                       "THE_BURDEN_BP_I_003.jpg":  {
                                                       "BC":  0,
                                                       "CM":  0,
                                                       "EF":  2,
                                                       "URM":  0,
                                                       "LS":  0,
                                                       "CT":  0,
                                                       "SM":  0,
                                                       "RT":  0,
                                                       "UA":  0
                                                   },
                       "THE_BURDEN_BP_I_005.jpg":  {
                                                       "BC":  0,
                                                       "CM":  0,
                                                       "EF":  0,
                                                       "URM":  0,
                                                       "LS":  0,
                                                       "CT":  0,
                                                       "SM":  0,
                                                       "RT":  2,
                                                       "UA":  0
                                                   },
                       "THE_BURDEN_BP_II_001.jpg":  {
                                                        "BC":  0,
                                                        "CM":  0,
                                                        "EF":  4,
                                                        "URM":  0,
                                                        "LS":  0,
                                                        "CT":  0,
                                                        "SM":  0,
                                                        "RT":  0,
                                                        "UA":  0
                                                    },
                       "THE_BURDEN_BP_I_001.jpg":  {
                                                       "BC":  0,
                                                       "CM":  0,
                                                       "EF":  2,
                                                       "URM":  0,
                                                       "LS":  0,
                                                       "CT":  0,
                                                       "SM":  0,
                                                       "RT":  0,
                                                       "UA":  0
                                                   },
                       "THE_BURDEN_BP_II_003.jpg":  {
                                                        "BC":  0,
                                                        "CM":  0,
                                                        "EF":  2,
                                                        "URM":  0,
                                                        "LS":  0,
                                                        "CT":  0,
                                                        "SM":  0,
                                                        "RT":  2,
                                                        "UA":  0
                                                    },
                       "THE_BURDEN_BP_II_002.jpg":  {
                                                        "BC":  0,
                                                        "CM":  0,
                                                        "EF":  0,
                                                        "URM":  0,
                                                        "LS":  0,
                                                        "CT":  0,
                                                        "SM":  0,
                                                        "RT":  4,
                                                        "UA":  0
                                                    },
                       "THE_BURDEN_BP_III_006.jpg":  {
                                                         "BC":  0,
                                                         "CM":  0,
                                                         "EF":  2,
                                                         "URM":  0,
                                                         "LS":  0,
                                                         "CT":  0,
                                                         "SM":  0,
                                                         "RT":  4,
                                                         "UA":  0
                                                     },
                       "THE_BURDEN_BP_I_006.jpg":  {
                                                       "BC":  0,
                                                       "CM":  0,
                                                       "EF":  0,
                                                       "URM":  0,
                                                       "LS":  0,
                                                       "CT":  0,
                                                       "SM":  0,
                                                       "RT":  2,
                                                       "UA":  0
                                                   },
                       "THE_BURDEN_BP_III_003.jpg":  {
                                                         "BC":  0,
                                                         "CM":  0,
                                                         "EF":  4,
                                                         "URM":  0,
                                                         "LS":  0,
                                                         "CT":  0,
                                                         "SM":  0,
                                                         "RT":  4,
                                                         "UA":  0
                                                     },
                       "THE_BURDEN_BP_III_004.jpg":  {
                                                         "BC":  0,
                                                         "CM":  0,
                                                         "EF":  2,
                                                         "URM":  0,
                                                         "LS":  0,
                                                         "CT":  0,
                                                         "SM":  0,
                                                         "RT":  2,
                                                         "UA":  0
                                                     },
                       "THE_BURDEN_BP_I_004.jpg":  {
                                                       "BC":  0,
                                                       "CM":  0,
                                                       "EF":  2,
                                                       "URM":  0,
                                                       "LS":  0,
                                                       "CT":  0,
                                                       "SM":  0,
                                                       "RT":  0,
                                                       "UA":  0
                                                   },
                       "THE_BURDEN_BP_III_001.jpg":  {
                                                         "BC":  0,
                                                         "CM":  0,
                                                         "EF":  4,
                                                         "URM":  0,
                                                         "LS":  0,
                                                         "CT":  0,
                                                         "SM":  0,
                                                         "RT":  0,
                                                         "UA":  0
                                                     },
                       "THE_BURDEN_BP_II_005.jpg":  {
                                                        "BC":  0,
                                                        "CM":  0,
                                                        "EF":  0,
                                                        "URM":  0,
                                                        "LS":  0,
                                                        "CT":  0,
                                                        "SM":  0,
                                                        "RT":  4,
                                                        "UA":  0
                                                    },
                       "THE_BURDEN_BP_II_006.jpg":  {
                                                        "BC":  0,
                                                        "CM":  0,
                                                        "EF":  2,
                                                        "URM":  0,
                                                        "LS":  0,
                                                        "CT":  0,
                                                        "SM":  0,
                                                        "RT":  2,
                                                        "UA":  0
                                                    },
                       "THE_BURDEN_BP_III_002.jpg":  {
                                                         "BC":  0,
                                                         "CM":  0,
                                                         "EF":  4,
                                                         "URM":  0,
                                                         "LS":  0,
                                                         "CT":  0,
                                                         "SM":  0,
                                                         "RT":  0,
                                                         "UA":  0
                                                     },
                       "THE_BURDEN_BP_I_002.jpg":  {
                                                       "BC":  0,
                                                       "CM":  0,
                                                       "EF":  0,
                                                       "URM":  0,
                                                       "LS":  0,
                                                       "CT":  0,
                                                       "SM":  0,
                                                       "RT":  2,
                                                       "UA":  0
                                                   }
                   }
};
